apiVersion: v1
kind: ConfigMap
metadata:
  name: main-api-configs
  labels:
    app: main-api-service
data:
  DB_URL: jdbc:postgresql://postgresql/crypto-cat-box
  DB_USER: root
  DB_PASS: qG9cU#CnvP@DNhVBG$4@$6e!6r69Q6b&
